spring.application.name=POS-System

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/pos_system
spring.datasource.username=root
spring.datasource.password=UTsav@9975

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=false

server.servlet.context-path=/api
jwt.secretKey = sddfhrhrphkroh009'.ovksdou0980908f0i0i009-fa-faspolomojopjfofkp,;kpjmopdkpdapfksopmdolmvoffpdspvk

